// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';
import {gui} from '../models';
import {config} from '../models';

export function GetConfig():Promise<Record<string, any>>;

export function GetConfigValue(arg1:string):Promise<any>;

export function GetDefaultRegexPatterns():Promise<Array<parser.RegexPattern>>;

export function GetFileList():Promise<Array<gui.FileInfo>>;

export function GetStats():Promise<gui.Stats>;

export function IsRunning():Promise<boolean>;

export function LoadConfig():Promise<Record<string, any>>;

export function ResetConfig():Promise<void>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;

export function SendFileStatus(arg1:gui.FileInfo):Promise<void>;

export function SendLog(arg1:string,arg2:string):Promise<void>;

export function SendProgress():Promise<void>;

export function SetConfigValue(arg1:string,arg2:any):Promise<void>;

export function Start(arg1:string):Promise<void>;

export function Stop():Promise<void>;

export function SuggestRegexPattern(arg1:string):Promise<Array<parser.RegexPattern>>;

export function TestNumberExtraction(arg1:string,arg2:string):Promise<Record<string, any>>;

export function TestRegexPattern(arg1:gui.RegexTestRequest):Promise<Array<parser.RegexTestResult>>;

export function ValidateConfig(arg1:config.Config):Promise<void>;

export function ValidateRegex(arg1:string):Promise<Record<string, any>>;
