// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['gui']['App']['GetConfig']();
}

export function GetConfigValue(arg1) {
  return window['go']['gui']['App']['GetConfigValue'](arg1);
}

export function GetDefaultRegexPatterns() {
  return window['go']['gui']['App']['GetDefaultRegexPatterns']();
}

export function GetFileList() {
  return window['go']['gui']['App']['GetFileList']();
}

export function GetStats() {
  return window['go']['gui']['App']['GetStats']();
}

export function IsRunning() {
  return window['go']['gui']['App']['IsRunning']();
}

export function LoadConfig() {
  return window['go']['gui']['App']['LoadConfig']();
}

export function ResetConfig() {
  return window['go']['gui']['App']['ResetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['gui']['App']['SaveConfig'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['gui']['App']['SelectFolder'](arg1);
}

export function SendFileStatus(arg1) {
  return window['go']['gui']['App']['SendFileStatus'](arg1);
}

export function SendLog(arg1, arg2) {
  return window['go']['gui']['App']['SendLog'](arg1, arg2);
}

export function SendProgress() {
  return window['go']['gui']['App']['SendProgress']();
}

export function SetConfigValue(arg1, arg2) {
  return window['go']['gui']['App']['SetConfigValue'](arg1, arg2);
}

export function Start(arg1) {
  return window['go']['gui']['App']['Start'](arg1);
}

export function Stop() {
  return window['go']['gui']['App']['Stop']();
}

export function SuggestRegexPattern(arg1) {
  return window['go']['gui']['App']['SuggestRegexPattern'](arg1);
}

export function TestNumberExtraction(arg1, arg2) {
  return window['go']['gui']['App']['TestNumberExtraction'](arg1, arg2);
}

export function TestRegexPattern(arg1) {
  return window['go']['gui']['App']['TestRegexPattern'](arg1);
}

export function ValidateConfig(arg1) {
  return window['go']['gui']['App']['ValidateConfig'](arg1);
}

export function ValidateRegex(arg1) {
  return window['go']['gui']['App']['ValidateRegex'](arg1);
}
